#===== SERVICE VALUES
PORT=7061
#HTTPS=true
NAME='controleg-parametricas'
DESCRIPTION='parametricas'
VERSION=1
SISCGE_CODIGO=0

#===== URL PARA AUTENTICACION
URL_AUTENTICACION = http://172.16.75.101:7010
# NO AGREGAR MAS VARIABLES, INCLUIRLOS EN LOS ENVS DE AUTENTICACION
