	
###PUT##
http://172.16.75.100:7002/informes-uai
{
	"act_codigo": 608,
	"act_descripcion": "INFORMES ANALÍTICOS DE LOS POA'S E INF. DE ACTIV ANUAL REMITIDOS POR LA UAI´S A LA CGE",
	"ampliacion": false,
	"emp_codigo": null,
	"emp_nombre": null,
	"ent_codigo": 64,
	"ent_descripcion": "ACADEMIA NACIONAL DE CIENCIAS",
	"fecha_baja": "01/01/1900 00:00",
	"fecha_modificacion": "01/01/1900 00:00",
	"fecha_registro": "18/06/2024 13:26",
	"ges_anio": 2024,
	"ges_codigo": 2,
	"informe_evaluacion": null,
	"inicio_evaluacion_informe": null,
	"iua_cite": "123",
	"iua_codigo": 572,
	"iua_codigo_control": "",
	"iua_correlativo": 0,
	"iua_est_color": "#54bebe",
	"iua_estado": 1,
	"iua_estado_descripcion": "EDICION",
	"iua_fecha": "18/06/2024",
	"iua_fecha_fin_evaluacion": null,
	"iua_fecha_inicio_evaluacion": null,
	"iua_hoja_ruta": "123test",
	"iua_referencia": "otros",
	"reingreso": null,
	"ttr_codigo": 77,
	"ttr_descripcion": "EVALUACIÓN DE FIRMAS",
	"ttr_inicial": "T",
	"usuario_baja": 0,
	"usuario_modificacion": 0,
	"usuario_registro": 819
}
