### ESTADO
###  -------- OBTENER - ITEM
  GET {{Host}}/estado
### AUTH INTERNO
  # @name login_interno
  POST http://172.16.75.100:7064/auth/interno HTTP/1.1
  Content-type: application/json

  {
    "usu_usuario": "4332293-1E",
    "usu_contrasenia": "AFC4332293-1E"
  }
### AUTH EXTERNO
  # @name login_interno
  POST http://172.16.75.100:7064/auth/externo HTTP/1.1
  Content-type: application/json

  {
    "usu_usuario": "3508438",
    "usu_contrasenia": "DZS3508438",
    "ent_codigo": 0
  }

### Este es token de autenticacion
  @AuthTokenInterno = {{login_interno.response.body.datos.token}}
  @AuthTokenExterno = Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjY2LCJlbnQiOjk4LCJwZXJuYXQiOjg1LCJpYXQiOjE3MTg0MDUyOTAsImV4cCI6MTcxODQzNDA5MH0.jbnMm7y8ra1KPBT3AJMv_GJFd62pETtmGcHN-dFkOHhSXntD4FmctZenkKPwYgD1hrDaZS-Uf-UTnMgep3x8prPO0qKKoAfM6KikiKSJ-HImP75V-LgIqGfwdxyp2899lCsxKLyFd5CAMpZHWGHB3F3ArBQaWutrfO7PiFxAEP1YGcKqbnX-ktRQGEI4CX9A-fDAFBcH6LskeQqhRAj9fnsYHrR4DRomVnWv8LC8Ju81E3YNHNXM4QegZWTl3n2BjHzfsEUkEXgfV2kHHXBc9UGIOk4EMaMzELZPQ3jbmf_H3QQ19phWMGaxxE57iTJiGSIvua174XeRcOkebCA96AY08Nf1gHGj_wIDhKuxfFM2-yTAVDdGPpTtixAbPHLJF5yu7gQDP3Pasdhy1qkSC-7knxZgiFX0L3flSqyeVdJebGQJDHOlCMZYDFbA6XbJUmvlGj536nGsJSmlVkMXmuAKOIZfg9NW0hJa8f1QE9XZP151DJOeSoCz1YxId2yFkLN3_jN2c_vmaJnetfFE2UHh03Vi34T3IoTu_bSebgXf_dzNj4Lo1IXuuIK3l8uruNUu8GTDO8rxvKVRyjXDgnxAjiB70F2wfOaPcS-T7kvpCx1SI75gZWyIWbzHxplZjba8LyPKauHBRSny2ypWymk3gixNBYj766zoHOc-cps
###   Aqui se define IP de servicio web
  @Host = http://172.16.75.100:7064
  @Hostautenticacion = http://172.16.22.241:7010/
  @tokenautenticacion = Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aXBvIjoic2lzdGVtYSIsInNpc3RlbWEiOiJTaXN0ZW1hIGRlIGF1dGVudGljYWNpb24iLCJzaWdsYSI6ImF1dGVudGljYWNpb24iLCJpZCI6IjZkNDEzYWE1LWQ2MjMtNGRkNC1hOWMxLTQ0OTVmMzRjOGI3MCIsInNpc3RlbWFzIjpbeyJzaXNjZ2VfY29kaWdvIjowLCJzaXNjZ2Vfc2lnbGEiOiJhdXRlbnRpY2FjaW9uIn1dLCJpYXQiOjE2MjA0MTAwNDN9.cE1CnVUfMf7Nieg0j22MBie9I7V1RRqyuFjngUFMcJfE0Gs3OYdfXTY0ovB_CJMyGLlrWn1TXVLFGXdcGxEnTA
### VARIABLES
  @tipproCodigo=20
  @estetaCodigo=5
  @estcontCodigo=10
  @estclaCodigo=1
  @tipresCodigo=3
### USUARIO
###  -------- OBTENER - USUARIO
  GET {{Host}}/usuario/ HTTP/1.1
  # GET {{Host}}/usuario/recursos?tipoRecurso=1 HTTP/1.1
  Authorization: {{AuthTokenExterno}}
  Content-Type: application/json
###  -------- OBTENER - USUARIO POST
  POST {{Host}}/usuario/find?usu_estado(1,2) HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "usuario": 2022,
    "usu_estado": 2
  }
### MENU-ROL
###  -------- OBTENER - MENU-ROL
  GET {{Host}}/menu-rol/ HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json
###  -------- OBTENER - MENU-ROL POST
  POST {{Host}}/menu-rol/find HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "usuario": 2022,
    "menrol_estado": 2
  }
###  -------- CREAR - MENU-ROL
  POST {{Host}}/menu-rol HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "men_codigo": 4,
    "rol_codigo": 4,
    "menrol_estado": 2,
    "usuario":2022
  }
###  -------- MODIFICAR - MENU-ROL
  PUT {{Host}}/menu-rol HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "menrol_codigo": 40,
    "men_codigo": 2,
    "rol_codigo": 4,
    "usuario":2022
  }
###  -------- ELIMINAR - MENU-ROL
  DELETE {{Host}}/menu-rol/38
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json
###  -------- ACTIVAR - MENU-ROL
  PATCH {{Host}}/menu-rol/38 HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

### MENU-USUARIO-ROL
###  -------- OBTENER - MENU-USUARIO-ROL
  GET {{Host}}/menu-usuario-rol/ HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json
###  -------- OBTENER - MENU-USUARIO-ROL POST
  POST {{Host}}/menu-usuario-rol/find HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "usuario": "1024",
    "menrol_estado": 1
  }
###  -------- CREAR - MENU-USUARIO-ROL
  POST {{Host}}/menu-usuario-rol HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "men_codigo": 2,
    "usurol_codigo": 1,
    "mur_estado": 2,
    "usuario":2022
  }
###  -------- MODIFICAR - MENU-USUARIO-ROL
  PUT {{Host}}/menu-usuario-rol HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "mur_codigo": 3,
    "men_codigo": 3,
    "usurol_codigo": 1,
    "usuario":2022
  }
###  -------- ELIMINAR - MENU-USUARIO-ROL
  DELETE {{Host}}/menu-usuario-rol/3
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json
###  -------- ACTIVAR - MENU-ROL
  PATCH {{Host}}/menu-usuario-rol/3 HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

### MENU-ROL-OPERACION
###  -------- OBTENER - MENU-ROL-OPERACION
  GET {{Host}}/menu-rol-operacion/ HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json
###  -------- OBTENER - MENU-ROL-OPERACION POST
  POST {{Host}}/menu-rol-operacion/find HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "usuario": "1024",
    "menrol_estado": 2
  }
###  -------- CREAR - MENU-ROL-OPERACION
  POST {{Host}}/menu-rol-operacion HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "menrol_codigo": 1,
    "ope_codigo": 2,
    "mro_estado": 2,
    "usuario":2022
  }
###  -------- MODIFICAR - MENU-ROL-OPERACION
  PUT {{Host}}/menu-rol-operacion HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "mro_codigo": 157,
    "menrol_codigo": 2,
    "ope_codigo": 2,
    "mro_estado": 2,
    "usuario":2022
  }
###  -------- ELIMINAR - MENU-ROL-OPERACION
  DELETE {{Host}}/menu-rol-operacion/157
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json
###  -------- ACTIVAR - MENU-ROL-OPERACION
  PATCH {{Host}}/menu-rol-operacion/157 HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json
### MENU-USUARIO-ROL-OPERACION
###  -------- OBTENER - MENU-USUARIO-ROL-OPERACION
  GET {{Host}}/menu-usuario-rol-operacion/ HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json
###  -------- OBTENER - MENU-USUARIO-ROL-OPERACION POST
  POST {{Host}}/menu-usuario-rol-operacion/find HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "usuario": "1024",
    "muro_estado": 2
  }
###  -------- CREAR - MENU-USUARIO-ROL-OPERACION
  POST {{Host}}/menu-usuario-rol-operacion HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "mur_codigo": 1,
    "ope_codigo": 2,
    "muro_estado": 2,
    "usuario":2022
  }
###  -------- MODIFICAR - MENU-USUARIO-ROL-OPERACION
  PUT {{Host}}/menu-usuario-rol-operacion HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "muro_codigo": 2,
    "mur_codigo": 1,
    "ope_codigo": 3,
    "muro_estado": 2,
    "usuario":2022
  }
###  -------- ELIMINAR - MENU-USUARIO-ROL-OPERACION
  DELETE {{Host}}/menu-usuario-rol-operacion/2
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json
###  -------- ACTIVAR - MENU-USUARIO-ROL-OPERACION
  PATCH {{Host}}/menu-usuario-rol-operacion/2 HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json
### RUTAS-DEPENDIENTES
###  -------- OBTENER - RUTAS-DEPENDIENTES
  GET {{Host}}/rutas-dependientes/ HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json
###  -------- OBTENER - RUTAS-DEPENDIENTES POST
  POST {{Host}}/rutas-dependientes/find HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "usuario": "1024",
    "rutdep_estado": 2
  }
###  -------- CREAR - RUTAS-DEPENDIENTES
  POST {{Host}}/rutas-dependientes HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "rutdep_ruta": "ruta 3",
    "rutdep_descripcion": "desc 3",
    "men_codigo": 1,
    "rutdep_estado": 2,
    "usuario":2022
  }
###  -------- MODIFICAR - RUTAS-DEPENDIENTES
  PUT {{Host}}/rutas-dependientes HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "rutdep_codigo": 3,
    "rutdep_ruta": "ruta 3",
    "rutdep_descripcion": "desc 3 3",
    "men_codigo": 1,
    "rutdep_estado": 2,
    "usuario":2022
  }
###  -------- ELIMINAR - RUTAS-DEPENDIENTES
  DELETE {{Host}}/rutas-dependientes/2
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json
###  -------- ACTIVAR - RUTAS-DEPENDIENTES
  PATCH {{Host}}/rutas-dependientes/2 HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json
### CONDICION - USUARIOS
###  -------- OBTENER - CONDICION - USUARIOS
  GET {{Host}}/condicion-usuario/ HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json
###  -------- OBTENER - CONDICION - USUARIOS POST
  POST {{Host}}/condicion-usuario/find HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "usuario": "1024",
    "rutdep_estado": 2
  }
###  -------- CREAR - CONDICION - USUARIOS
  POST {{Host}}/condicion-usuario HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "conusu_justificacion": "just prueba 3",
    "conusu_fecha_inicio": "2024-06-17",
    "conusu_fecha_final": "2024-09-17",
    "con_codigo": 16,
    "usu_codigo": 3,
    "usuario":2022
  }
###  -------- MODIFICAR - CONDICION - USUARIOS
  PUT {{Host}}/condicion-usuario HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json

  {
    "rutdep_codigo": 3,
    "rutdep_ruta": "ruta 3",
    "rutdep_descripcion": "desc 3 3",
    "men_codigo": 1,
    "rutdep_estado": 2,
    "usuario":2022
  }
###  -------- ELIMINAR - CONDICION - USUARIOS
  DELETE {{Host}}/condicion-usuario/6
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json
###  -------- ACTIVAR - CONDICION - USUARIOS
  PATCH {{Host}}/condicion-usuario/6 HTTP/1.1
  Authorization: {{AuthTokenInterno}}
  Content-Type: application/json